# This is a basic workflow to help you get started with Actions

name: pub_patch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: install node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "14.x"
      - name: install deps
        run: npm install
      - name:  'Login github'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.LOGTHEME_TOKEN }}
        with:
          default: prerelease
          rc-wording:     'RELEASE,alpha,PicX'
      - name: publish patch
        run: npm run pub:patch
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
